//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHat
    {
        public int id { get; set; }
        public string tenbaihat { get; set; }
        public string tencasi { get; set; }
        public string path { get; set; }
        public int luotnghe { get; set; }
        public bool yeuthich { get; set; }
        public string loibaihat { get; set; }
    }
}
